version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 901446182982.dkr.ecr.ap-south-1.amazonaws.com

  build:
    commands:
      - docker build -t performance .
      - docker tag performance:latest 901446182982.dkr.ecr.ap-south-1.amazonaws.com/performance:latest
      - docker push 901446182982.dkr.ecr.ap-south-1.amazonaws.com/performance:latest